SELECT * FROM EMP;
SELECT EMPNO AS 사원번호, ENAME AS 사원명 FROM EMP WHERE DEPTNO=30;

SELECT * FROM EMP WHERE DEPTNO=30 AND JOB='SALESMAN';
SELECT * FROM EMP WHERE DEPTNO=30 OR JOB='CLERK';

SELECT * FROM EMP WHERE SAL >= 3000;

SELECT * FROM EMP WHERE ENAME>='F';

SELECT * FROM EMP WHERE SAL !=3000;
SELECT * FROM EMP WHERE SAL <>3000;
SELECT * FROM EMP WHERE SAL ^=3000;

SELECT * FROM EMP WHERE NOT SAL=3000;

SELECT * FROM EMP WHERE JOB='MANAGER' OR JOB='SALESMAN' OR JOB='CLERK';
SELECT * FROM EMP WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');

SELECT * FROM EMP WHERE JOB != 'MANAGER' AND JOB != 'SALESMAN' AND JOB != 'CLERK';
SELECT * FROM EMP WHERE JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK');
