SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 3000;
SELECT * FROM EMP WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT ENAME FROM EMP WHERE ENAME LIKE 'S%';
SELECT ENAME FROM EMP WHERE ENAME LIKE 's%';
SELECT ENAME FROM EMP WHERE ENAME LIKE '_L%';
SELECT ENAME FROM EMP WHERE ENAME LIKE '%AM%';
SELECT ENAME FROM EMP WHERE ENAME NOT LIKE '%AM%';

SELECT * FROM EMP;
SELECT * FROM EMP WHERE COMM = NULL;
SELECT * FROM EMP WHERE COMM IS NULL;
SELECT ENAME, MGR FROM EMP;
SELECT ENAME, JOB FROM EMP WHERE MGR IS NOT NULL;
SELECT ENAME, JOB FROM EMP;

SELECT * FROM EMP WHERE SAL > NULL AND COMM IS NULL;
SELECT * FROM EMP WHERE SAL > NULL OR COMM IS NULL;

SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 20;

DESC EMP;
DESC DEPT;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL FROM EMP WHERE DEPTNO = 20;
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
UNION
SELECT ENAME, EMPNO, DEPTNO, SAL FROM EMP WHERE DEPTNO = 20;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO=10;

SELECT * FROM EMP WHERE ENAME LIKE '%S';
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO=30 AND JOB='SALESMAN';
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO=20 AND SAL>2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO=30 AND SAL > 2000;
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE (DEPTNO=20 OR DEPTNO=30) AND SAL>2000;
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO IN (20,30) AND SAL>2000;
SELECT * FROM EMP WHERE NOT SAL>=2000 AND SAL<=3000;
SELECT * FROM EMP WHERE SAL <2000 OR SAL>3000;
SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP
 WHERE ENAME LIKE '%E%' AND DEPTNO=30 AND SAL NOT BETWEEN 1000 AND 2000;
SELECT * FROM EMP
 WHERE COMM IS NULL AND MGR IS NOT NULL AND JOB IN ('MANAGER','CLERK') AND ENAME NOT LIKE '_L%';
 
 SELECT COUNT(*) FROM EMP;
 
 SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME) FROM EMP;