SELECT SAL+300 FROM EMP;

SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL FROM EMP ORDER BY ANNSAL DESC;

SELECT ENAME, SAL FROM EMP WHERE SAL>2000 ORDER BY SAL DESC;

SELECT ENAME, DEPTNO FROM EMP WHERE EMPNO=7788;

SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO IN(20,30) ORDER BY DEPTNO DESC;

SELECT ENAME, SAL, DEPTNO FROM EMP WHERE SAL BETWEEN 2000 AND 3000 AND DEPTNO IN(20,30) ORDER BY ENAME ASC;

SELECT ENAME FROM EMP WHERE ENAME LIKE '__R%';


SELECT LENGTH('ABC'), LENGTH('한글') FROM DUAL;
SELECT LENGTHB('ABC'), LENGTHB('한글') FROM DUAL;

SELECT JOB,SUBSTR(JOB,1,2), SUBSTR(JOB,3,2),SUBSTR(JOB,5) FROM EMP;
SELECT JOB,SUBSTR(JOB,-LENGTH(JOB)), SUBSTR(JOB,-LENGTH(JOB),2),SUBSTR(JOB,-3) FROM EMP;

SELECT INSTR('HELLO, ORACLE!','L') FROM DUAL;
SELECT INSTR('HELLO, ORACLE!','L',5) FROM DUAL;
SELECT INSTR('HELLO, ORACLE!','L',2,2) FROM DUAL;
SELECT * FROM EMP WHERE INSTR(ENAME,'S') >0;
SELECT * FROM EMP WHERE ENAME LIKE '%S%';

SELECT '010-1234-5678' AS 변경전,
    REPLACE('010-1234-5678','-',' ')AS 변경후1,
    REPLACE('010-1234-5678','-') AS 변경후2 
  FROM DUAL;

SELECT 'ORACLE',
    LPAD('ORACLE',10,'#'),
    LPAD('ORACLE',10),
    RPAD('ORACLE',10,'#'),
    RPAD('ORACLE',10)
  FROM DUAL;

SELECT * FROM EMP;
SELECT LPAD(JOB,10,'#') FROM EMP;
SELECT LPAD(JOB,10) FROM EMP;

SELECT RPAD('971225-',14,'*'),
       RPAD('010-1234-',13,'*')
  FROM DUAL;
  
SELECT CONCAT(EMPNO,ENAME) FROM EMP;
SELECT CONCAT(EMPNO,CONCAT(' : ',ENAME)) FROM EMP;

SELECT 'test' || ' : ' || 'test1' FROM DUAL;
SELECT '사원의 이름은 ' || ENAME || ' 입니다' FROM EMP;

SELECT '[' || ' Oracle ' || ']' FROM DUAL;
SELECT '[' || TRIM(' _ _Oracle_ _ ') || ']' FROM DUAL;
SELECT '[' || TRIM(LEADING FROM ' Oracle ') || ']' FROM DUAL;
SELECT '[' || TRIM(TRAILING FROM ' Oracle ') || ']' FROM DUAL;
SELECT '[' || TRIM(BOTH FROM ' Oracle ') || ']' FROM DUAL; 

SELECT '[' || LTRIM(' _Oracle_ ') || ']' from dual;
SELECT '[' || RTRIM(' _Oracle_ ') || ']' from dual;
SELECT '[' || LTRIM('<_Oracle_>','<_') || ']' from dual;

SELECT ROUND(1234.5678),
       ROUND(1234.5678,0),
       ROUND(1234.5678,1),
       ROUND(1234.5678,2),
       ROUND(1234.5678,-1),
       ROUND(1234.5678,-2)
  FROM DUAL;
  
SELECT TRUNC(1234.5678),
       TRUNC(1234.5678,0),
       TRUNC(1234.5678,1),
       TRUNC(1234.5678,2)
  FROM DUAL;