SELECT ENAME, HIREDATE FROM EMP WHERE SUBSTR(HIREDATE,1,4)=1981;
SELECT HIREDATE FROM EMP;
DESC EMP;

SELECT ENAME,JOB,SAL FROM EMP WHERE JOB IN ('CLERK','SALESMAN') AND SAL !=1600 AND SAL !=950 AND SAL !=1300;

SELECT NVL(MGR,0) FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL,
       DECODE(JOB,
              'MANAGER', SAL*1.1,
              'SALESMAN', SAL*1.05,
              'ANALYST', SAL,
              SAL*1.03) AS UPSAL
    FROM EMP;
    
SELECT EMPNO, ENAME, JOB, SAL,
    CASE JOB
         WHEN 'MANAGER' THEN SAL*1.1
         WHEN 'SALESMAN' THEN SAL*1.05
         WHEN 'ANALYST' THEN SAL
         ELSE SAL*1.03
    END AS UPSAL
  FROM EMP;
SELECT EMPNO, ENAME, COMM,
    CASE
      WHEN COMM IS NULL THEN '해당사항 없음'
      WHEN COMM = 0 THEN '수당없음'
      WHEN COMM > 0 THEN '수당 : ' || COMM
    END AS COMM_TEXT
  FROM EMP;
  

SELECT EMPNO, RPAD(SUBSTR(EMPNO,1,2),4,'*') AS MAKING_EMPNO, ENAME, RPAD(SUBSTR(ENAME,1,1),5,'*') AS MASKING_ENAME
  FROM EMP
  WHERE LENGTH(ENAME) >= 5 AND LENGTH(ENAME) < 6;
  
SELECT ENAME,
     CASE LENGTH(ENAME)
       WHEN 5 THEN RPAD(SUBSTR(ENAME,1,1),5,'*')
       WHEN 6 THEN RPAD(SUBSTR(ENAME,1,1),6,'*')
       ELSE RPAD(SUBSTR(ENAME,1,1),4,'*')
     END AS MAKING_ENAME
  FROM EMP;
  
SELECT ENAME, RPAD(SUBSTR(ENAME,1,1),4,'*') AS MAKING_ENAME
  FROM EMP
  WHERE LENGTH(ENAME)= 4
UNION
SELECT ENAME, RPAD(SUBSTR(ENAME,1,1),5,'*') AS MAKING_ENAME
  FROM EMP
  WHERE LENGTH(ENAME)= 5
UNION
SELECT ENAME, RPAD(SUBSTR(ENAME,1,1),6,'*') AS MAKING_ENAME
  FROM EMP
  WHERE LENGTH(ENAME)= 6;
  
SELECT ENAME, RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') AS MAKING_ENMAE
  FROM EMP; 