SELECT NVL(COMM,0) FROM EMP;
SELECT NVL(TO_CHAR(COMM),'해당없음') FROM EMP;

SELECT EMPNO, ENAME, HIREDATE, 
  TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE,3),'월요일'),'YYYY-MM-DD') AS R_JOB,
  NVL(TO_CHAR(COMM),'N/A') AS COMM
  FROM EMP;
  
SELECT EMPNO, ENAME, MGR,
   CASE 
        WHEN MGR IS NULL THEN '0000'
        WHEN SUBSTR(MGR,1,2)='75' THEN '5555'
        WHEN SUBSTR(MGR,1,2)='76' THEN '6666'
        WHEN SUBSTR(MGR,1,2)='77' THEN '7777'
        WHEN SUBSTR(MGR,1,2)='78' THEN '8888'
        ELSE TO_CHAR(MGR)
    END AS CHG_MGR
  FROM EMP;
  

SELECT SUM(COMM) FROM EMP;
SELECT SUM(DISTINCT SAL), SUM(ALL SAL), SUM(SAL) FROM EMP;

SELECT COUNT(COMM) FROM EMP;
SELECT COUNT(*) FROM EMP;
SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO=30;
SELECT COUNT(*) FROM EMP WHERE DEPTNO=30; -- 6명
SELECT COUNT(*) FROM EMP WHERE DEPTNO=10; -- 3명
SELECT COUNT(*) FROM EMP WHERE DEPTNO=20; -- 5명
SELECT COUNT(DISTINCT SAL), COUNT(ALL SAL), COUNT(SAL) FROM EMP;
SELECT COUNT(COMM) FROM EMP; -- 수당 지급과 관련된 사원의 수, 결과 : 4
SELECT COMM FROM EMP;
SELECT COUNT(COMM) FROM EMP WHERE COMM IS NOT NULL; -- 결과 : 4

SELECT MAX(SAL) FROM EMP WHERE DEPTNO=10; -- 10번 부서의 최대 급여, 결과 : 5000
SELECT SAL FROM EMP WHERE DEPTNO=10;
SELECT MIN(SAL) FROM EMP WHERE DEPTNO=10; -- 10번 부서의 최소 급여, 결과 : 1300
SELECT MAX(HIREDATE) FROM EMP WHERE DEPTNO=20; -- 20번 부서의 가장 최근 입사한 사원의 입사일, 결과 : 1987/05/23
SELECT MIN(HIREDATE) FROM EMP WHERE DEPTNO=20; -- 20번 부서의 가장 오래된 사원의 입사일, 결과 : 1980/12/17
SELECT TRUNC(AVG(SAL)) AS 평균급여 FROM EMP WHERE DEPTNO=30; -- 30번 부서의 평균 급여

SELECT TRUNC(AVG(SAL)),DEPTNO FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO, JOB, AVG(SAL)
  FROM EMP
  GROUP BY DEPTNO, JOB
    HAVING AVG(SAL)>=2000
  ORDER BY DEPTNO, JOB;
  

-- Q1
SELECT DEPTNO, TRUNC(AVG(SAL)) AS AVG_SAL, 
       MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL, COUNT(*) AS CNT
  FROM EMP
  GROUP BY DEPTNO;
-- Q2  
SELECT JOB, COUNT(*)
  FROM EMP
  GROUP BY JOB
    HAVING COUNT(*)>=3;
-- Q3    
SELECT SUBSTR(HIREDATE,1,4) AS HIRE_YEAR, DEPTNO, COUNT(*) AS CNT
  FROM EMP
  GROUP BY SUBSTR(HIREDATE,1,4),DEPTNO;
SELECT TO_CHAR(HIREDATE,'YYYY') AS HIRe_YEAR, DEPTNO, COUNT(*) AS CNT
  FROM EMP
  GROUP BY TO_CHAR(HIREDATE,'YYYY'),DEPTNO;
-- Q4
SELECT NVL2(COMM,'O','X') AS EXIST_COMM, COUNT(*) AS CNT
  FROM EMP
  GROUP BY NVL2(COMM,'O','X');
-- COUNT() 이용하여 담당업무가 동일한 사원 수
SELECT JOB, COUNT(*) AS CNT
  FROM EMP
  GROUP BY JOB;
-- 직급별 사원의 최저 급여
SELECT JOB, MIN(SAL) AS 최저급여
  FROM EMP
  GROUP BY JOB;
-- 급여가 평균 급여보다 많은 모든 사원의 사원 번호와 사원 이름
-- SELECT AVG(SAL) FROM EMP;
SELECT EMPNO, ENAME, SAL
  FROM EMP
  WHERE SAL > (SELECT AVG(SAL) FROM EMP);
