-- 사원의 이름과 사원이 속한 부서의 부서 이름을 출력
--SELECT * FROM EMP, DEPT;
SELECT E.ENAME AS 사원이름, D.DNAME AS 부서이름
  FROM EMP E, DEPT D
  WHERE E.DEPTNO = D.DEPTNO
  ORDER BY D.DNAME;
SELECT ENAME AS 사원이름, DNAME AS 부서이름
  FROM EMP NATURAL JOIN DEPT
  ORDER BY DNAME;
-- SMITH 사원이 속한 부서이름
SELECT E.ENAME AS 사원이름, D.DNAME AS 부서이름 
  FROM EMP E, DEPT D
  WHERE E.DEPTNO = D.DEPTNO AND E.ENAME='SMITH';
SELECT ENAME AS 사원이름, DNAME AS 부서이름 
  FROM EMP JOIN DEPT USING (DEPTNO)
  WHERE ENAME LIKE 'SMITH';
-- 급여가 2000 이상인 사원들의 사원이름, 급여, 부서명 (급여 기준으로 내림차순 정렬)
SELECT E.ENAME AS 사원이름, E.SAL AS 급여, D.DNAME AS 부서명
  FROM EMP E, DEPT D
  WHERE E.DEPTNO = D.DEPTNO AND SAL >= 2000
  ORDER BY SAL DESC;
SELECT E.ENAME AS 사원이름, E.SAL AS 급여, D.DNAME AS 부서명
  FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
  WHERE SAL >= 2000
  ORDER BY SAL DESC;


-- 단일행 서브쿼리(실행 결과 한 개)
SELECT * FROM EMP
  WHERE SAL > (SELECT SAL 
                 FROM EMP
                 WHERE ENAME = 'JONES');
SELECT ENAME, HIREDATE FROM EMP WHERE ENAME='SCOTT'; -- 1987/04/19
SELECT * FROM EMP
  WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME='SCOTT');
SELECT AVG(SAL) FROM EMP; -- 평균 급여 (전체 사원) : 2073
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
  WHERE E.DEPTNO = D.DEPTNO AND E.DEPTNO = 20
    AND E.SAL > (SELECT AVG(SAL) FROM EMP);

-- BLAKE 사원보다 급여가 많은 사원들의 정보 출력
SELECT * FROM EMP
  WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='BLAKE');
-- 부서별 최대 급여를 받는 사원들의 사원번호, 사원이름, 부서번호, 급여 출력
SELECT EMPNO AS 사원번호, ENAME AS 사원이름, DEPTNO AS 부서번호, SAL AS 급여
  FROM EMP
  WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);
-- JOB이 CLERK인 사원이 2명 이상 있는 부서의 부서번호, 부서이름
SELECT DEPTNO FROM EMP WHERE JOB='CLERK'; -- 20
--SELECT * FROM DEPT;
SELECT DEPTNO AS 부서번호, DNAME AS 부서이름 -- RESEARCH
  FROM DEPT 
  WHERE DEPTNO = (SELECT DEPTNO FROM EMP
                    WHERE JOB='CLERK'
                    GROUP BY DEPTNO
                    HAVING COUNT(*)>=2);

-- 다중행 서브쿼리(실행 결과 여러 개; IN 연산자)
SELECT * FROM EMP WHERE DEPTNO IN (20,30);
SELECT * FROM EMP WHERE DEPTNO IN (20);
SELECT * FROM EMP
  WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO); -- 2850, 3000, 5000
  
-- 각 부서별로 최소 급여를 받는 사원의 부서번호, 부서이름, 사원번호, 사원이름, 급여 출력(JOIN ~ ON 사용)
SELECT MIN(SAL) FROM EMP GROUP BY DEPTNO;
SELECT D.DEPTNO AS 부서번호, D.DNAME AS 부서이름, E.EMPNO AS 사원번호, E.ENAME AS 사원이름, E.SAL AS 급여
  FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
  WHERE SAL IN (SELECT MIN(SAL) FROM EMP GROUP BY DEPTNO);
-- 평균 급여보다 많거나 같고 최대 급여보다는 적은 급여를 받는 사원의 사원번호, 사원이름, 급여 출력
SELECT AVG(SAL), MAX(SAL) FROM EMP; -- AVG : 2073, MAX : 5000
SELECT EMPNO AS 사원번호, ENAME AS 사원이름, SAL AS 급여
  FROM EMP
  WHERE SAL >= (SELECT AVG(SAL) FROM EMP)
    AND SAL < (SELECT MAX(SAL) FROM EMP);

-- Q1
SELECT E.JOB,E.EMPNO,E.ENAME,E.SAL,D.DEPTNO,D.DNAME
  FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
  WHERE E.JOB = (SELECT JOB FROM EMP WHERE ENAME='ALLEN');
-- Q2
SELECT * FROM SALGRADE;
SELECT * FROM EMP E, SALGRADE S WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, S.GRADE
  FROM EMP E, DEPT D, SALGRADE S
  WHERE E.DEPTNO = D.DEPTNO 
    AND E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND SAL > (SELECT AVG(SAL) FROM EMP)
  ORDER BY SAL DESC, E.EMPNO;
-- Q3
SELECT JOB FROM EMP WHERE DEPTNO=30; -- SALESMAN, MANAGER, CLERK
SELECT E.EMPNO, E.ENAME, E.JOB, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
  WHERE D.DEPTNO = 10 -- MANAGER,PRESIDENT, CLERK
    AND JOB NOT IN (SELECT DISTINCT JOB FROM EMP WHERE DEPTNO=30); -- RPESIDENT
-- Q4
SELECT MAX(SAL) FROM EMP WHERE JOB='SALESMAN'; -- 1600
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
  FROM EMP E, SALGRADE S
  WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB='SALESMAN')
  ORDER BY E.EMPNO;