-- 데이터 정의어
-- TABLE 생성
CREATE TABLE EMP1 (EMPNO NUMBER(4), ENAME VARCHAR2(10), MGR NUMBER(4), DEPTNO NUMBER(2) );
DESC EMP1;
-- TABLE 삭제
DROP TABLE EMP1;

-- TABLE에 데이터 추가
INSERT INTO EMP1 VALUES(7369,'SMITH',7902,20);
INSERT INTO EMP1 VALUES(7902,'FORD',7566,20);
INSERT INTO EMP1 VALUES(7566,'JONES',7839,20);
INSERT INTO EMP1 VALUES(7839,'KING',NULL,20);

SELECT * FROM EMP1;
/*
7369	SMITH	7902	20
7902	FORD	7566	20
7566	JONES	7839	20
7839	KING		    20
*/

-- SELF JOIN
SELECT * FROM EMP1 E1, EMP1 E2; -- EMP1 TABLE의 행의 갯수 : 4 -> 4 * 4 = 16 개
SELECT * FROM EMP1 E1, EMP1 E2 WHERE E1.MGR = E2.EMPNO;
SELECT E1.EMPNO AS 사원번호, E1.ENAME AS 사원명, E2.ENAME AS 상사 
  FROM EMP1 E1, EMP1 E2 
  WHERE E1.MGR = E2.EMPNO(+);

-- 다중행 서브쿼리
SELECT * FROM EMP 
  WHERE SAL < ANY (SELECT SAL FROM EMP WHERE DEPTNO =30)
  ORDER BY SAL, EMPNO;
SELECT * FROM EMP 
  WHERE SAL > ANY (SELECT SAL FROM EMP WHERE DEPTNO =30)
  ORDER BY SAL, EMPNO;
SELECT * FROM EMP 
  WHERE SAL < ALL (SELECT SAL FROM EMP WHERE DEPTNO =30)
  ORDER BY SAL, EMPNO;
SELECT * FROM EMP 
  WHERE SAL > ALL (SELECT SAL FROM EMP WHERE DEPTNO =30)
  ORDER BY SAL, EMPNO;
SELECT * FROM EMP
  WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO = 10);
SELECT * FROM DEPT;
SELECT * FROM EMP
  WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO = 50);


-- 실습
-- SALES 부서에 속한 사원 중에서 그 부서의 평균 급여보다 더 높은 급여를 받는 사원의 사원명과 급여
SELECT E.ENAME AS 사원명, E.SAL AS 급여
  FROM EMP E, DEPT D
  WHERE E.DEPTNO = D.DEPTNO AND D.DNAME LIKE 'SALES'
    AND SAL > (SELECT AVG(SAL) FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO) WHERE DNAME = 'SALES');
/*
SELECT ENAME, SAL FROM EMP E
  WHERE
    (SELECT DNAME FROM DEPT D WHERE E.DEPTNO = D.DEPTNO)='SALES'
    AND SAL > (SELECT AVG(SAL) FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE DNAME='SALES');
*/
 -- FROM절에 서브쿼리 사용 가능
SELECT AVG(SAL)
  FROM (SELECT D.DNAME, SAL FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND D.DNAME='SALES'); -- AVG = 1566

-- 비교할 열이 여러 개인 다중열 서브쿼리
SELECT MAX(SAL) FROM EMP WHERE DEPTNO =10; -- 5000
SELECT MAX(SAL) FROM EMP WHERE DEPTNO =20; -- 3000
SELECT MAX(SAL) FROM EMP WHERE DEPTNO =30; -- 2850
SELECT * FROM EMP WHERE (DEPTNO,SAL) IN (SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO);

-- FROM 절에서 서브쿼리 사용 (인라인 뷰; INLINE VIEW)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
  FROM (SELECT * FROM EMP WHERE DEPTNO =10) E10,
    (SELECT * FROM DEPT) D
  WHERE E10.DEPTNO = D.DEPTNO; -- 결과값 3개
SELECT COUNT(DEPTNO) FROM EMP WHERE DEPTNO=10; -- 3
-- WITH 절
WITH
E10 AS (SELECT * FROM EMP WHERE DEPTNO =10),
D AS (SELECT * FROM DEPT)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
  FROM E10, D
  WHERE E10.DEPTNO=D.DEPTNO;


-- 테이블 생성
CREATE TABLE DEPT_TEMP AS SELECT * FROM DEPT; -- 테이블 복사
SELECT * FROM DEPT_TEMP;
DROP TABLE DEPT_TEMP;
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES (50, 'DATABASE','SEOUL');
DESC DEPT_TEMP;
INSERT INTO DEPT_TEMP VALUES (60, 'NETWORK','BUSAN'); -- 열 지정 생략
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES (70, 'WEB',NULL); -- NULL 데이터 입력
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES (80, 'MOBILE',''); -- NULL 데이터 입력
INSERT INTO DEPT_TEMP (DEPTNO, LOC) VALUES (90, 'INCHEON');

CREATE TABLE EMP_TEMP AS (SELECT * FROM EMP WHERE 1 <> 1); -- 열 구조만 복사(데이터는 복사 X)
SELECT * FROM EMP_TEMP;
DESC EMP_TEMP;
SELECT HIREDATE FROM EMP;
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (9999,'홍길동', 'PRESIDENT', NULL, '2001/01/01', 5000, 1000, 10);
--DROP TABLE EMP_TEMP;
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (1111,'성춘향', 'MANAGER', 9999, '2001-01-05', 4000, NULL, 20);
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (2111,'이순신', 'MANAGER', 9999, '07/01/2001', 4000, NULL, 20); -- 날짜 형식이 다르면 오류 발생하고 데이터 입력 X
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (2111,'이순신', 'MANAGER', 9999, TO_DATE('07/01/2001','DD/MM/YYYY'), 4000, NULL, 20);
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (3111,'심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30); -- SYSDATE 사용