CREATE TABLE DEPT_TEMP2 AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP2;

-- 테이블에 있는 데이터 수정 UPDATE
-- 전체 수정
UPDATE DEPT_TEMP2
  SET LOC='SEOUL';
-- 내용 되돌리기
ROLLBACK;
-- 일부 수정
UPDATE DEPT_TEMP2
  SET DNAME='DATABASE', LOC='SEOUL'
  WHERE DEPTNO=40;     
-- 서브쿼리 이용
UPDATE DEPT_TEMP2
  SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO=40)
  WHERE DEPTNO = 40;
UPDATE DEPT_TEMP2
  SET LOC = 'SEOUL'
  WHERE DEPTNO = (SELECT DEPTNO FROM DEPT_TEMP2 WHERE DNAME='OPERATIONS');

UPDATE DEPT_TEMP2
  SET DNAME = 'MARKETING'
  WHERE DEPTNO = (SELECT DEPTNO FROM DEPT_TEMP2 WHERE DEPTNO = 30);


CREATE TABLE EMP_TEMP2 AS SELECT * FROM EMP;
SELECT * FROM EMP_TEMP2;
-- 테이블 삭제 DELETE
-- WHERE 조건절에 해당하는 행 삭제
DELETE FROM EMP_TEMP2 WHERE JOB = 'MANAGER';
-- 서브쿼리 이용
DELETE FROM EMP_TEMP2
  WHERE EMPNO IN (SELECT E.EMPNO
                    FROM EMP_TEMP2 E, SALGRADE S
                    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                      AND S.GRADE = 3 AND DEPTNO = 30);
-- 데이터 전체 삭제
DELETE FROM EMP_TEMP2;


CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;
-- Q1
INSERT INTO CHAP10HW_DEPT VALUES (50, 'ORACLE', 'BUSAN');
INSERT INTO CHAP10HW_DEPT VALUES (60, 'SQL', 'ILSAN');
INSERT INTO CHAP10HW_DEPT VALUES (70, 'SELECT', 'INCHEON');
INSERT INTO CHAP10HW_DEPT VALUES (80, 'DML', 'BUNDANG');
SELECT * FROM CHAP10HW_DEPT;
-- Q2
INSERT INTO CHAP10HW_EMP VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('2016-01-02', 'YYYY-MM-DD'), 4500, NULL, 50);
INSERT INTO CHAP10HW_EMP VALUES (7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('2016-02-21', 'YYYY-MM-DD'), 1800, NULL, 50);
INSERT INTO CHAP10HW_EMP VALUES (7203, 'TEST_USER3', 'ANALYST', 7201, TO_DATE('2016-04-11', 'YYYY-MM-DD'), 3400, NULL, 60);
INSERT INTO CHAP10HW_EMP VALUES (7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('2016-05-31', 'YYYY-MM-DD'), 2700, 300, 60);
INSERT INTO CHAP10HW_EMP VALUES (7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('2016-07-20', 'YYYY-MM-DD'), 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP VALUES (7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('2016-09-08', 'YYYY-MM-DD'), 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP VALUES (7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('2016-10-28', 'YYYY-MM-DD'), 2300, NULL, 80);
INSERT INTO CHAP10HW_EMP VALUES (7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('2018-03-09', 'YYYY-MM-DD'), 1200, NULL, 80);
SELECT * FROM CHAP10HW_EMP;
-- Q3
UPDATE CHAP10HW_EMP
  SET DEPTNO = 70
  WHERE SAL > (SELECT AVG(SAL) FROM CHAP10HW_EMP WHERE DEPTNO=50); -- AVG(SAL)=3150
--SELECT * FROM CHAP10HW_EMP WHERE DEPTNO =70;
--Q4
UPDATE CHAP10HW_EMP
  SET SAL = SAL*1.1, DEPTNO = 80
  WHERE HIREDATE > (SELECT HIREDATE FROM CHAP10HW_EMP WHERE DEPTNO=60); -- 2016-05-31
--Q5
DELETE FROM CHAP10HW_EMP
  WHERE EMPNO IN (SELECT E.EMPNO
                    FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S
                    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                      AND S.GRADE = 5); --KING, USER1,USER3

-- 데이터 정의어(DDL; DATA DEFINITION LANGUAGE)
-- COMMINT; 지금까지 한 작업을 DB에 적용, 실행취소 불가(ROLLBACK 불가)
/* NUMBER(4) - 숫자형 데이터/자릿수 : 4자리
   VARCHAR2(10) - 문자형 데이터/문자열 길이 : 10자리, 가변형 문자열
   NUMBER(7,2) - 숫자형 데이터/ ,2(소숫점 자리) */
-- CREATE : 테이블 생성
CREATE TABLE EMP_DDL(
  EMPNO NUMBER(4), 
  ENMAE VARCHAR2(10),
  JOB VARCHAR2(9),
  MGR NUMBER(4),
  HIREDATE DATE,
  SAL NUMBER(7,2),
  COMM NUMBER(7,2),
  DEPTNO NUMBER(2)
  );
SELECT * FROM EMP_DDL;
DESC EMP_DDL;
-- 일부 데이터만 복사
CREATE TABLE EMP_DDL_30
  AS SELECT * FROM EMP WHERE DEPTNO=30;
SELECT * FROM EMP_DDL_30;
-- 열 구조만 복사
CREATE TABLE EMPDEPT_DDL
  AS SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
       FROM EMP E, DEPT D
       WHERE 1 <> 1;
SELECT * FROM EMPDEPT_DDL;

-- ALTER : 테이블 변경
CREATE TABLE EMP_ALTER AS SELECT * FROM EMP;
SELECT * FROM EMP_ALTER;
-- 열 추가
ALTER TABLE EMP_ALTER ADD HP VARCHAR2(20);
UPDATE EMP_ALTER SET HP = '010-1234-5678';
-- 열 이름 변경
ALTER TABLE EMP_ALTER RENAME COLUMN HP TO TEL;
-- 열의 자료형(데이터유형) 변경
ALTER TABLE EMP_ALTER MODIFY EMPNO NUMBER(5);
DESC EMP_ALTER;
-- 특정 열 삭제
ALTER TABLE EMP_ALTER DROP COLUMN TEL;

-- RENAME 테이블 이름 변경
RENAME EMP_ALTER TO EMP_RENAME;
SELECT * FROM EMP_ALTER;
SELECT * FROM EMP_RENAME;
-- TRUNCATE 테이블의 데이터 삭제
TRUNCATE TABLE EMP_RENAME;
ROLLBACK; -- ROLLBACK으로 데이터 복구 불가
-- DROP 테이블 삭제
DROP TABLE EMP_RENAME;


--Q1
CREATE TABLE EMP_HW(
  EMPNO NUMBER(4),
  ENAME VARCHAR2(10),
  JOB VARCHAR2(9),
  MGR NUMBER(4),
  HIREDATE DATE,
  SAL NUMBER(7,2),
  COMM NUMBER(7,2),
  DEPTNO NUMBER(2)
  );
DESC EMP_HW;
--Q2
ALTER TABLE EMP_HW ADD BIGO VARCHAR2(20);
--Q3
ALTER TABLE EMP_HW MODIFY BIGO VARCHAR2(30);
--Q4
ALTER TABLE EMP_HW RENAME COLUMN BIGO TO REMARK;
--Q5
INSERT INTO EMP_HW SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL FROM EMP;
SELECT * FROM EMP_HW;
--Q6
DROP TABLE EMP_HW;


--실습
-- 학교 운동부 테이블 만들기
-- 팀 테이블 : 팀아이디(4), 지역, 팀명, 개설날짜, 전화번호, 홈페이지
-- 선수 테이블 : 선수번호, 선수명, 등록일, 포지션(NULL), 키(3), 팀아이디
-- 2개의 팀 작성, 2개의 팀에는 3명의 선수 등록
DROP TABLE SCHOOL_TEAM;
CREATE TABLE SCHOOL_TEAM (
  팀아이디 NUMBER(4),
  지역 VARCHAR2(10),
  팀명 VARCHAR2(10),
  개설날짜 DATE,
  전화번호 VARCHAR2(20),
  홈페이지 VARCHAR2(30)
  );
CREATE TABLE TEAM_STUDENT(
  선수번호 NUMBER(4),
  선수명 VARCHAR2(10),
  등록일 DATE,
  포지션 VARCHAR2(20),
  키 NUMBER(3),
  팀아이디 NUMBER(4)
  );
INSERT INTO SCHOOL_TEAM VALUES (1001, 'SEOUL', 'SO_TEAM', TO_DATE('2016-10-31','YYYY-MM-DD'), '02-123-456', 'www.seoul.com');
INSERT INTO SCHOOL_TEAM VALUES (2001, 'DAEGU', 'DA_TEAM', TO_DATE('2017-10-31','YYYY-MM-DD'), '053-456-789', 'www.daegu.com');
SELECT * FROM SCHOOL_TEAM;
INSERT INTO TEAM_STUDENT VALUES (1010, 'SMITH', TO_DATE('2016-12-30','YYYY-MM-DD'),NULL, 180, 1001);
INSERT INTO TEAM_STUDENT VALUES (1011, 'ALLEN', TO_DATE('2016-12-31','YYYY-MM-DD'),NULL, 178, 1001);
INSERT INTO TEAM_STUDENT VALUES (1012, 'WARD', TO_DATE('2017-01-05','YYYY-MM-DD'),NULL, 183, 1001);
INSERT INTO TEAM_STUDENT VALUES (2010, 'JONES', TO_DATE('2017-11-02','YYYY-MM-DD'),NULL, 179, 2001);
INSERT INTO TEAM_STUDENT VALUES (2011, 'MARTIN', TO_DATE('2017-11-25','YYYY-MM-DD'),NULL, 180, 2001);
INSERT INTO TEAM_STUDENT VALUES (2012, 'BLAKE', TO_DATE('2017-12-01','YYYY-MM-DD'),NULL, 185, 2001);
SELECT * FROM TEAM_STUDENT;
