-- VIEW 생성
CREATE VIEW VM_EMP20
  AS (SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO=20);
SELECT * FROM VM_EMP20;
-- 생성한 뷰 확인
SELECT * FROM USER_VIEWS;
-- 뷰 삭제
--DROP VIEW VW_EMP20;
-- 인라인 뷰
-- ROWNUM(행 번호)
SELECT ROWNUM, E.* FROM EMP E ORDER BY SAL DESC;
SELECT ROWNUM, E.*
  FROM (SELECT * FROM EMP E ORDER BY SAL DESC) E
  WHERE ROWNUM <= 3;
-- 시퀀스(SEQUENCE)
CREATE TABLE DEPT_SEQUENCE AS SELECT * FROM DEPT WHERE 1 <> 1;
SELECT * FROM DEPT_SEQUENCE;
-- 시퀀스 생성
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
  INCREMENT BY 10 -- 10만큼 증가
  START WITH 10 -- 10부터 시작
  MAXVALUE 90 -- 최댓값
  MINVALUE 0 -- 최솟값
  NOCYCLE -- 반복 X
  CACHE 2;
SELECT * FROM USER_SEQUENCES; -- 생성한 시퀀스 확인
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
  VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');
SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;
-- 시퀀스 삭제
DROP SEQUENCE SEQ_DEPT_SEQUENCE;
-- CURRVAL (마지막으로 생성한 번호 반환)
-- 시퀀스를 생성하고 바로 사용하면 번호가 만들어진 적이 없으므로 오류 남
SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;
-- NEXTVAL (다음 번호 생성)
SELECT SEQ_DEPT_SEQUENCE.NEXTVAL FROM DUAL;
-- 시퀀스 수정
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
  INCREMENT BY 3   
  MAXVALUE 99 
  CYCLE;
SELECT * FROM USER_SEQUENCES; -- 생성한 시퀀스 확인
SELECT * FROM DEPT_SEQUENCE;
---------------------------------------------------------
-- 다시 시작
DELETE FROM DEPT_SEQUENCE WHERE DNAME='DATABASE';
DELETE SEQUENCE SEQ_DEPT_SEQUENCE;

-------------------------------------------------------
CREATE TABLE DEPT_SEQ AS SELECT * FROM DEPT WHERE 1 <> 1;
CREATE SEQUENCE SEQ_DEPT_SEQ
  INCREMENT BY 10 -- 10만큼 증가
  START WITH 10 -- 10부터 시작
  MAXVALUE 90 -- 최댓값
  MINVALUE 0 -- 최솟값
  NOCYCLE -- 반복 X
  CACHE 2; -- 미리 번호 만듦
SELECT * FROM DEPT_SEQ;
DELETE FROM DEPT_SEQ WHERE DNAME='DATABASE';
SELECT SEQ_DEPT_SEQ.NEXTVAL FROM DUAL;
SELECT * FROM USER_SEQUENCES; -- DD
INSERT INTO DEPT_SEQ (DEPTNO, DNAME, LOC) VALUES (SEQ_DEPT_SEQ.NEXTVAL, 'DATABASE', 'SEOUL');
ALTER SEQUENCE SEQ_DEPT_SEQ
  INCREMENT BY 3   
  MAXVALUE 99 
  CYCLE; -- 96 99 0 3 ...
SELECT * FROM USER_SEQUENCES; -- DD
INSERT INTO DEPT_SEQ (DEPTNO, DNAME, LOC) VALUES (SEQ_DEPT_SEQ.NEXTVAL, 'DATABASE', 'SEOUL');
SELECT * FROM DEPT_SEQ;

DROP SEQUENCE SEQ_DEPT_SEQ;
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

-- 동의어(공식 별칭 지정)
CREATE SYNONYM E FOR EMP;
SELECT * FROM E;
DROP SYNONYM E;

-----------------------------------------------------------------
SELECT * FROM USER_SEQUENCES;
CREATE SEQUENCE SEQ_DEPT_SEQ
  INCREMENT BY 10 -- 10만큼 증가
  START WITH 10 -- 10부터 시작
  MAXVALUE 90 -- 최댓값
  MINVALUE 0 -- 최솟값
  NOCYCLE -- 반복 X
  NOCACHE;
CREATE TABLE DEPT_TMP3 AS SELECT * FROM DEPT WHERE 1 <> 1;
INSERT INTO DEPT_TMP3 VALUES (SEQ_DEPT_SEQ.NEXTVAL,'DATABASE','SEOUL');
SELECT * FROM DEPT_TMP3;


CREATE TABLE EMPIDX AS SELECT * FROM EMP;
SELECT * FROM EMPIDX;
--Q2
CREATE VIEW EMPIDX_OVER15K
  AS (SELECT EMPNO, ENAME, JOB, DEPTNO, SAL, NVL2(COMM,'O','X') AS COMM
        FROM EMP 
        WHERE SAL > 1500);
SELECT * FROM EMPIDX_OVER15K;
--Q3
CREATE TABLE DEPTSEQ AS SELECT * FROM DEPT WHERE 1 <> 1;
SELECT * FROM DEPTSEQ;
CREATE SEQUENCE SEQ_DPETSEQ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99
  MINVALUE 1
  NOCYCLE
  NOCACHE;
SELECT * FROM USER_SEQUENCES; -- 생성된 시퀀스 확인
INSERT INTO DEPTSEQ VALUES (SEQ_DEPTSEQ.NEXTVAL, 'DATABASE','SEOUL');
INSERT INTO DEPTSEQ VALUES (SEQ_DEPTSEQ.NEXTVAL, 'WEB','BUSAN');
INSERT INTO DEPTSEQ VALUES (SEQ_DEPTSEQ.NEXTVAL, 'MOBILE','ILSAN');
SELECT * FROM DEPTSEQ;
--DROP TABLE DEPTSEQ;
--DROP SEQUENCE SEQ_DPETSEQ;
--SELECT * FROM SEQ_DPETSEQ; -- 시퀀스가 허용되지 않습니다 =? ORA-02201

-- INDEX(인덱스)
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS; -- DD 확인
CREATE INDEX IDX_EMP_SAL ON EMP(SAL);
DROP INDEX IDX_EMP_SAL;

--Q1
CREATE INDEX IDX_EMPIDX_EMPNO ON EMPIDX(EMPNO);
SELECT * FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_EMPIDX_EMPNO';
--SELECT * FROM USER_IND_COLUMNS WHERE INDEX_NAME = 'IDX_EMPIDX_EMPNO';
